### ISSUE TITLE
error: No module named cement.core

### ISSUE THREAD

**Issue by ozett** [philchristensen/python-artnet#3]
i just coned it out from git and was given it a try. but i got this error:

```
Installed /usr/local/lib/python2.7/dist-packages/python_artnet-0.1-py2.7.egg
Processing dependencies for python-artnet==0.1
Finished processing dependencies for python-artnet==0.1
root@ubuntu:~/python-artnet# artnet script all_channels_full
Traceback (most recent call last):
  File "/usr/local/bin/artnet", line 9, in <module>
    load_entry_point('python-artnet==0.1', 'console_scripts', 'artnet')()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/python_artnet-0.1-py2.7.egg/artnet/scripts/__init__.py", line 4, in <module>
    from cement.core import foundation, controller, handler
ImportError: No module named cement.core
root@ubuntu:~/python-artnet# artnet script all_channels_full --address=192.168.14.59
Traceback (most recent call last):
  File "/usr/local/bin/artnet", line 9, in <module>
    load_entry_point('python-artnet==0.1', 'console_scripts', 'artnet')()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/python_artnet-0.1-py2.7.egg/artnet/scripts/__init__.py", line 4, in <module>
    from cement.core import foundation, controller, handler
ImportError: No module named cement.core
root@ubuntu:~/python-artnet#

```

any hints to solve this? i a no python expert ....

**Comment by galloxD** [comment]
now you have to install cement with the following command:
pip install cement==2.10.2
